"""
Lemlist integration: the connection, and the data imported through it.

Three decisions shape these tables.

**The CRM is the source of truth for reads.** Nothing in the application queries lemlist to render a
screen. Everything imported lands here and is read from here, so the Contacts page does not inherit
lemlist's latency, its rate limit (20 requests per 2 seconds, shared across the whole workspace), or its
downtime. Webhooks and a nightly reconcile keep it current.

**Imported prospects are kept apart from the CRM's own contact directory.** `contacts` requires an
`account_id` — a contact belongs to a filed company, which is what lets the directory group by company and
what makes the champion gate meaningful. A lemlist lead has a free-text `companyName` and nothing else, and
a cold outreach list is mostly companies nobody has decided to work. Forcing every imported lead into
`contacts` would mean inventing an account per company name, which would fill the accounts table with
prospects and defeat the duplicate detection that exists to keep it clean. So imported leads live here,
and `LemlistContact.contact_id` records a *promotion*: when somebody decides this prospect is real, they
become a filed contact at a filed account, and the link keeps the outreach history attached.

**Everything is keyed on lemlist's own ids.** Every table carries the remote id under a unique constraint
scoped to the connection, so an import is idempotent: re-running it updates rather than duplicates, which
is what makes both the nightly reconcile and a webhook arriving twice safe.
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin


class LemlistConnection(UUIDMixin, TimestampMixin, Base):
    """
    One user's link to their own lemlist workspace.

    Per user, not per installation: the plan is that each rep connects their own account, and the API key
    is theirs. That also means the key must never be readable by anybody else, which is why it is stored
    encrypted and never returned by any endpoint — see `app.core.secrets`.

    One row per user, enforced by a unique constraint. Reconnecting overwrites rather than accumulating,
    so there is never a question of which of two keys is live.
    """

    __tablename__ = "lemlist_connections"
    __table_args__ = (UniqueConstraint("user_id", name="uq_lemlist_connections_user_id"),)

    user_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    #: Fernet ciphertext, never plaintext, and never serialised out of the API.
    api_key_encrypted: Mapped[str] = mapped_column(Text, nullable=False)
    #: First eight hex characters of the key's SHA-256, so the UI can say *which* key we hold without
    #: showing any part of the key itself.
    api_key_fingerprint: Mapped[str] = mapped_column(String(16), nullable=False)

    #: lemlist's own workspace identifiers, from `GET /team` at connect time.
    team_id: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    team_name: Mapped[str] = mapped_column(String(255), nullable=False, default="")

    connected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    #: When anything was last read from lemlist for this workspace — a campaign list or a campaign import.
    #: Null means nothing ever has been.
    last_sync_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    #: Why the last read failed, kept so the UI can say what went wrong instead of only that it did.
    #: Cleared on the next success.
    last_sync_error: Mapped[str] = mapped_column(Text, nullable=False, default="", server_default="")

    # There is deliberately no `sync_status` here. A stored status flag on this row was being used as a
    # lock over a request that took minutes, and one interrupted import left it stuck at `syncing`,
    # refusing every later attempt with a 409 about a run that no longer existed. Import state now lives on
    # the campaign being imported, where the work actually is, and the workspace-level status the API
    # reports is *derived* from those campaigns — so there is no stored value left to go stale.

    #: Shared with lemlist when registering a webhook and echoed back in every callback, so an inbound
    #: POST can be attributed to a workspace and rejected if it cannot be. Generated by us, stored
    #: encrypted for the same reason the key is: it is an authenticator.
    webhook_secret_encrypted: Mapped[str] = mapped_column(
        Text, nullable=False, default="", server_default=""
    )

    user: Mapped["User"] = relationship()  # noqa: F821
    campaigns: Mapped[list["LemlistCampaign"]] = relationship(
        back_populates="connection", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<LemlistConnection user={self.user_id} team={self.team_id!r}>"


class LemlistCampaign(UUIDMixin, TimestampMixin, Base):
    """
    A campaign imported from lemlist.

    `raw` keeps the payload as it arrived. lemlist's campaign object carries senders, creators and
    scheduling that this application has no use for today, and re-fetching the whole workspace to answer a
    later question about data we already had would be the wrong trade against one JSONB column.
    """

    __tablename__ = "lemlist_campaigns"
    __table_args__ = (
        UniqueConstraint("connection_id", "lemlist_id", name="uq_lemlist_campaigns_remote"),
    )

    connection_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("lemlist_connections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    lemlist_id: Mapped[str] = mapped_column(String(120), nullable=False)

    name: Mapped[str] = mapped_column(String(255), nullable=False, default="")
    status: Mapped[str] = mapped_column(String(60), nullable=False, default="")
    #: lemlist's timestamps, not ours. Null when the payload omitted them rather than defaulted to now,
    #: because a made-up creation date is worse than a missing one.
    remote_created_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    remote_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    lead_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    raw: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict, server_default="{}")

    #: When this campaign's leads and activity were last mirrored. Null means listed but never imported,
    #: which is the normal state for most of a workspace: campaigns are cheap to list and expensive to
    #: import, so the user picks which ones matter.
    #:
    #: This is the field that makes an import informed rather than forbidden. A campaign already mirrored
    #: is not re-fetched by default, but it is always refreshable — leads change state and activity keeps
    #: arriving, so a permanent block would freeze the mirror at whatever it happened to catch.
    imported_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    #: When the running import started, and null otherwise. The lock lives here rather than on the
    #: connection so importing one campaign never blocks another, and a crash strands one campaign
    #: instead of the whole integration.
    import_started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    #: Why the last import of *this* campaign failed. Per campaign because that is the unit that fails:
    #: "a campaign failed" is not actionable, and this is what lets the row say which and why.
    import_error: Mapped[str] = mapped_column(Text, nullable=False, default="", server_default="")

    connection: Mapped[LemlistConnection] = relationship(back_populates="campaigns")
    contacts: Mapped[list["LemlistContact"]] = relationship(
        back_populates="campaign", cascade="all, delete-orphan"
    )


class LemlistContact(UUIDMixin, TimestampMixin, Base):
    """
    A lead imported from a lemlist campaign.

    Identity is `(connection, campaign, email)` rather than lemlist's lead id, and that is a deliberate
    trade. The export endpoint — the primary import route — returns lead *fields* and does not reliably
    carry the same `_id` the activity and webhook payloads use, while email is present in every one of
    them and is what lemlist itself deduplicates a campaign on. `lemlist_lead_id` is recorded whenever it
    is seen, and is what webhooks are matched on first; email is the fallback that makes the match work
    when a webhook arrives for a lead the export described without an id.

    The same person appearing in two campaigns is two rows on purpose. Their state is per campaign — opened
    in one, bounced in another — and collapsing them would have to pick one of two contradictory answers.
    """

    __tablename__ = "lemlist_contacts"
    __table_args__ = (
        UniqueConstraint("campaign_id", "email", name="uq_lemlist_contacts_campaign_email"),
        # Webhooks arrive with a lead id and no campaign, so this is the lookup that has to be fast.
        Index("ix_lemlist_contacts_lead_id", "connection_id", "lemlist_lead_id"),
        Index("ix_lemlist_contacts_email", "connection_id", "email"),
    )

    connection_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("lemlist_connections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    campaign_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("lemlist_campaigns.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    lemlist_lead_id: Mapped[str] = mapped_column(String(120), nullable=False, default="", server_default="")
    email: Mapped[str] = mapped_column(String(320), nullable=False)

    first_name: Mapped[str] = mapped_column(String(160), nullable=False, default="", server_default="")
    last_name: Mapped[str] = mapped_column(String(160), nullable=False, default="", server_default="")
    company_name: Mapped[str] = mapped_column(String(255), nullable=False, default="", server_default="")
    job_title: Mapped[str] = mapped_column(String(255), nullable=False, default="", server_default="")
    phone: Mapped[str] = mapped_column(String(60), nullable=False, default="", server_default="")
    linkedin_url: Mapped[str] = mapped_column(String(500), nullable=False, default="", server_default="")

    #: lemlist's lead state — `emailsOpened`, `interested`, `meetingBooked` and so on. Kept as the string
    #: lemlist sent rather than mapped onto an enum of our own: lemlist adds states (it has separate ones
    #: for LinkedIn, WhatsApp and SMS steps), and an enum would turn every new one into a failed import.
    state: Mapped[str] = mapped_column(String(80), nullable=False, default="", server_default="")
    #: When anything last happened to this lead, from the latest engagement. Denormalised because the
    #: Contacts page sorts on it, and a correlated max() per row does not belong in a list query.
    last_activity_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    #: lemlist's custom variables, whatever the user defined. Free-form by nature, so JSONB rather than a
    #: guess at columns.
    variables: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict, server_default="{}")

    #: Set when somebody promotes this prospect into the CRM's own directory. `SET NULL` rather than
    #: cascade: deleting a filed contact should not silently destroy the outreach history that led to them.
    contact_id: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("contacts.id", ondelete="SET NULL"), nullable=True, index=True
    )

    campaign: Mapped[LemlistCampaign] = relationship(back_populates="contacts")
    engagements: Mapped[list["LemlistEngagement"]] = relationship(
        back_populates="contact", cascade="all, delete-orphan"
    )

    @property
    def full_name(self) -> str:
        """What to show. Falls back to the email, because a lead with no name is common and still real."""
        joined = f"{self.first_name} {self.last_name}".strip()
        return joined or self.email


class LemlistEngagement(UUIDMixin, TimestampMixin, Base):
    """
    One thing that happened to a lead: an open, a click, a reply, a booked meeting, a bounce.

    `lemlist_activity_id` is unique per connection, and that constraint is the whole idempotency story.
    Webhooks are at-least-once by nature and the nightly reconcile deliberately re-reads a window that
    overlaps what webhooks already delivered, so the same open arrives more than once as a matter of
    routine. The database refusing the duplicate is what keeps an engagement count honest.

    Webhook payloads do not always carry an activity id. Those rows get a synthetic one built from the
    event, the lead and the timestamp — the same three facts that make two events the same event — so
    replaying a webhook is still a no-op.
    """

    __tablename__ = "lemlist_engagements"
    __table_args__ = (
        UniqueConstraint("connection_id", "lemlist_activity_id", name="uq_lemlist_engagements_remote"),
        # The timeline for one lead, newest first. Compound because the sort is always inside one contact.
        Index("ix_lemlist_engagements_timeline", "lemlist_contact_id", "occurred_at"),
    )

    connection_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("lemlist_connections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    lemlist_contact_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("lemlist_contacts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    lemlist_activity_id: Mapped[str] = mapped_column(String(200), nullable=False)
    #: lemlist's event type, unmapped, for the reason given on `LemlistContact.state`.
    kind: Mapped[str] = mapped_column(String(80), nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    #: Which campaign step, the sending mailbox, the error message on a bounce — kept whole rather than
    #: sampled into columns, because what matters differs entirely by event type.
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict, server_default="{}")
    #: True when this arrived by webhook rather than by import, so a reconcile can report what it caught
    #: that webhooks missed — which is the only way to know whether webhook delivery is actually working.
    from_webhook: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )

    contact: Mapped[LemlistContact] = relationship(back_populates="engagements")


class LemlistWebhook(UUIDMixin, TimestampMixin, Base):
    """
    A webhook registered with lemlist on this connection's behalf.

    Recorded locally so registration is idempotent and so disconnecting can *deregister*: a hook left
    behind on lemlist's side keeps posting to an endpoint that no longer knows the workspace, which is
    both noise and a slow leak of somebody's outreach data into a system they thought they had unlinked.
    """

    __tablename__ = "lemlist_webhooks"
    __table_args__ = (
        UniqueConstraint("connection_id", "lemlist_hook_id", name="uq_lemlist_webhooks_remote"),
    )

    connection_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("lemlist_connections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    lemlist_hook_id: Mapped[str] = mapped_column(String(120), nullable=False)
    target_url: Mapped[str] = mapped_column(String(500), nullable=False)
    #: Empty means "all events", which is what omitting `type` means to lemlist.
    event_type: Mapped[str] = mapped_column(String(80), nullable=False, default="", server_default="")
