"""lemlist integration tables

Revision ID: 2e17bd7d5af5
Revises: b5d72e0af183
Create Date: 2026-08-12

Five tables: the per-user connection holding an encrypted API key, and the campaigns, leads, engagements
and registered webhooks imported through it. See `app/models/lemlist.py` for why imported leads are kept
apart from the CRM's own `contacts` table rather than merged into it.

Hand-edited after autogenerate, and worth saying why: autogenerate also proposed replacing
`accounts.name_normalized`'s trigram and partial-unique indexes with a plain btree, because it cannot read
either kind back from the database and so believes they are missing. Applying that would have silently
destroyed the duplicate-account detection. Only the lemlist operations were kept.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2e17bd7d5af5'
down_revision: Union[str, None] = 'b5d72e0af183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lemlist_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_key_fingerprint', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.String(length=120), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), server_default='', nullable=False),
    sa.Column('sync_status', sa.Enum('idle', 'syncing', 'error', name='lemlist_sync_status'), nullable=False),
    sa.Column('webhook_secret_encrypted', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lemlist_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lemlist_connections')),
    sa.UniqueConstraint('user_id', name='uq_lemlist_connections_user_id')
    )
    op.create_index(op.f('ix_lemlist_connections_user_id'), 'lemlist_connections', ['user_id'], unique=False)
    op.create_table('lemlist_campaigns',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('lemlist_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('remote_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['lemlist_connections.id'], name=op.f('fk_lemlist_campaigns_connection_id_lemlist_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lemlist_campaigns')),
    sa.UniqueConstraint('connection_id', 'lemlist_id', name='uq_lemlist_campaigns_remote')
    )
    op.create_index(op.f('ix_lemlist_campaigns_connection_id'), 'lemlist_campaigns', ['connection_id'], unique=False)
    op.create_table('lemlist_webhooks',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('lemlist_hook_id', sa.String(length=120), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.String(length=80), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['lemlist_connections.id'], name=op.f('fk_lemlist_webhooks_connection_id_lemlist_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lemlist_webhooks')),
    sa.UniqueConstraint('connection_id', 'lemlist_hook_id', name='uq_lemlist_webhooks_remote')
    )
    op.create_index(op.f('ix_lemlist_webhooks_connection_id'), 'lemlist_webhooks', ['connection_id'], unique=False)
    op.create_table('lemlist_contacts',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lemlist_lead_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=160), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=160), server_default='', nullable=False),
    sa.Column('company_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('job_title', sa.String(length=255), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=60), server_default='', nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), server_default='', nullable=False),
    sa.Column('state', sa.String(length=80), server_default='', nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['lemlist_campaigns.id'], name=op.f('fk_lemlist_contacts_campaign_id_lemlist_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['lemlist_connections.id'], name=op.f('fk_lemlist_contacts_connection_id_lemlist_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_lemlist_contacts_contact_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lemlist_contacts')),
    sa.UniqueConstraint('campaign_id', 'email', name='uq_lemlist_contacts_campaign_email')
    )
    op.create_index(op.f('ix_lemlist_contacts_campaign_id'), 'lemlist_contacts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lemlist_contacts_connection_id'), 'lemlist_contacts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_lemlist_contacts_contact_id'), 'lemlist_contacts', ['contact_id'], unique=False)
    op.create_index('ix_lemlist_contacts_email', 'lemlist_contacts', ['connection_id', 'email'], unique=False)
    op.create_index('ix_lemlist_contacts_lead_id', 'lemlist_contacts', ['connection_id', 'lemlist_lead_id'], unique=False)
    op.create_table('lemlist_engagements',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('lemlist_contact_id', sa.UUID(), nullable=False),
    sa.Column('lemlist_activity_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('from_webhook', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['lemlist_connections.id'], name=op.f('fk_lemlist_engagements_connection_id_lemlist_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lemlist_contact_id'], ['lemlist_contacts.id'], name=op.f('fk_lemlist_engagements_lemlist_contact_id_lemlist_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lemlist_engagements')),
    sa.UniqueConstraint('connection_id', 'lemlist_activity_id', name='uq_lemlist_engagements_remote')
    )
    op.create_index(op.f('ix_lemlist_engagements_connection_id'), 'lemlist_engagements', ['connection_id'], unique=False)
    op.create_index(op.f('ix_lemlist_engagements_lemlist_contact_id'), 'lemlist_engagements', ['lemlist_contact_id'], unique=False)
    op.create_index('ix_lemlist_engagements_timeline', 'lemlist_engagements', ['lemlist_contact_id', 'occurred_at'], unique=False)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lemlist_engagements_timeline', table_name='lemlist_engagements')
    op.drop_index(op.f('ix_lemlist_engagements_lemlist_contact_id'), table_name='lemlist_engagements')
    op.drop_index(op.f('ix_lemlist_engagements_connection_id'), table_name='lemlist_engagements')
    op.drop_table('lemlist_engagements')
    op.drop_index('ix_lemlist_contacts_lead_id', table_name='lemlist_contacts')
    op.drop_index('ix_lemlist_contacts_email', table_name='lemlist_contacts')
    op.drop_index(op.f('ix_lemlist_contacts_contact_id'), table_name='lemlist_contacts')
    op.drop_index(op.f('ix_lemlist_contacts_connection_id'), table_name='lemlist_contacts')
    op.drop_index(op.f('ix_lemlist_contacts_campaign_id'), table_name='lemlist_contacts')
    op.drop_table('lemlist_contacts')
    op.drop_index(op.f('ix_lemlist_webhooks_connection_id'), table_name='lemlist_webhooks')
    op.drop_table('lemlist_webhooks')
    op.drop_index(op.f('ix_lemlist_campaigns_connection_id'), table_name='lemlist_campaigns')
    op.drop_table('lemlist_campaigns')
    op.drop_index(op.f('ix_lemlist_connections_user_id'), table_name='lemlist_connections')
    op.drop_table('lemlist_connections')
    # The enum type outlives the table that used it, so dropping the table is not enough — a later
    # re-upgrade would fail on CREATE TYPE with "already exists".
    op.execute('DROP TYPE IF EXISTS lemlist_sync_status')
    # ### end Alembic commands ###
