"""lemlist import becomes per-campaign

Revision ID: 4b1e7c9d2a56
Revises: 2e17bd7d5af5
Create Date: 2026-08-13

Importing the whole workspace in one request was wrong in two ways that this migration settles.

It was too long: paced at 150ms a request to stay inside lemlist's budget, thirty-three campaigns took a
minute and a large workspace would take many, so the request routinely outlived the browser waiting on it.
And `lemlist_connections.sync_status` was being used as a lock over that request — a stored flag written by
one process and cleared only by the same one. One interrupted import left it at `syncing` forever, refusing
every later attempt with a 409 about a run that no longer existed.

So import state moves to the campaign being imported, which is where the work is, and the workspace-level
status the API reports is now *derived* from those campaigns — leaving no stored value that can go stale.
The column is dropped rather than left unused, because a dead status column is one somebody will read.

`imported_at` is backfilled for campaigns that already hold leads: they were mirrored by the old flow, and
calling them un-imported would offer a fresh import of data already present. `created_at` is the honest
stamp available — the old schema never recorded when a campaign's leads were last read.

Hand-written rather than autogenerated: autogenerate cannot read back the trigram and partial-unique indexes
on `accounts.name_normalized` and proposes dropping them, which would take duplicate-account detection with
it.
"""

import sqlalchemy as sa
from alembic import op

revision: str = "4b1e7c9d2a56"
down_revision: str | None = "2e17bd7d5af5"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.add_column(
        "lemlist_campaigns",
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "lemlist_campaigns",
        sa.Column("import_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "lemlist_campaigns",
        sa.Column("import_error", sa.Text(), nullable=False, server_default=""),
    )

    # A campaign with leads was imported by the old whole-workspace sync. Treating it as never imported
    # would invite a re-import of data that is already here.
    op.execute(
        "UPDATE lemlist_campaigns SET imported_at = created_at WHERE lead_count > 0"
    )

    op.drop_column("lemlist_connections", "sync_status")
    # The enum type is dropped with its last user. Left behind it would be an unreferenced type that the
    # next autogenerate run would notice and argue about.
    op.execute("DROP TYPE IF EXISTS lemlist_sync_status")


def downgrade() -> None:
    sync_status = sa.Enum("idle", "syncing", "error", name="lemlist_sync_status")
    sync_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "lemlist_connections",
        sa.Column("sync_status", sync_status, nullable=False, server_default="idle"),
    )
    op.drop_column("lemlist_campaigns", "import_error")
    op.drop_column("lemlist_campaigns", "import_started_at")
    op.drop_column("lemlist_campaigns", "imported_at")
