"""initial schema

Revision ID: 50b273f73188
Revises: 
Create Date: 2026-07-30 16:33:14.678646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '50b273f73188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('direct', 'partner', name='pipeline_type'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_pipeline_templates_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'rep', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('is_partner', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_accounts_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_is_partner'), 'accounts', ['is_partner'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_table('stages',
    sa.Column('pipeline_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('kind', sa.Enum('open', 'won', 'lost', name='stage_kind'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('entry_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exit_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name=op.f('ck_stages_position_positive')),
    sa.CheckConstraint('probability >= 0 AND probability <= 100', name=op.f('ck_stages_probability_range')),
    sa.CheckConstraint('wip_limit IS NULL OR wip_limit >= 0', name=op.f('ck_stages_wip_limit_non_negative')),
    sa.ForeignKeyConstraint(['pipeline_template_id'], ['pipeline_templates.id'], name=op.f('fk_stages_pipeline_template_id_pipeline_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stages')),
    sa.UniqueConstraint('pipeline_template_id', 'position', deferrable=True, initially='DEFERRED', name='uq_stage_pipeline_position')
    )
    op.create_index(op.f('ix_stages_pipeline_template_id'), 'stages', ['pipeline_template_id'], unique=False)
    op.create_table('leads',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_leads_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_leads_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_table('deals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_template_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('partner_id IS NULL OR partner_id <> account_id', name=op.f('ck_deals_partner_not_customer')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_deals_value_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_deals_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_deals_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_deals_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_id'], ['accounts.id'], name=op.f('fk_deals_partner_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_template_id'], ['pipeline_templates.id'], name=op.f('fk_deals_pipeline_template_id_pipeline_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_deals_stage_id_stages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_account_id'), 'deals', ['account_id'], unique=False)
    op.create_index(op.f('ix_deals_expected_close_date'), 'deals', ['expected_close_date'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deals_partner_id'), 'deals', ['partner_id'], unique=False)
    op.create_index(op.f('ix_deals_pipeline_template_id'), 'deals', ['pipeline_template_id'], unique=False)
    op.create_index(op.f('ix_deals_stage_id'), 'deals', ['stage_id'], unique=False)
    op.create_table('activities',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('call', 'meeting', 'email', 'note', 'stage-change', name='activity_kind'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(account_id, lead_id, deal_id) = 1', name=op.f('ck_activities_exactly_one_subject')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_activities_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_activities_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_activities_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_activities_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_account_id'), 'activities', ['account_id'], unique=False)
    op.create_index(op.f('ix_activities_author_id'), 'activities', ['author_id'], unique=False)
    op.create_index(op.f('ix_activities_deal_id'), 'activities', ['deal_id'], unique=False)
    op.create_index(op.f('ix_activities_lead_id'), 'activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_activities_occurred_at'), 'activities', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_occurred_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_lead_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_deal_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_author_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_account_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_deals_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_pipeline_template_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_partner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_expected_close_date'), table_name='deals')
    op.drop_index(op.f('ix_deals_account_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_stages_pipeline_template_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_partner'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pipeline_templates')
    # ### end Alembic commands ###
