"""Replace the pipeline type enum with a tracks_partner flag

Revision ID: 7c1e4a02b8d3
Revises: 50b273f73188
Create Date: 2026-07-31

The `type` column was an enum of exactly ('direct', 'partner'), which capped the system at
two pipelines and contradicted spec 6.2's "extensible". It was also only ever read to
decide one thing — whether deals on this pipeline show a Partner alongside the Customer —
so that question becomes its own boolean and the pipeline name becomes free text.

Hand-written rather than autogenerated: autogenerate would drop the column and add the
flag as two unrelated operations, losing which pipelines were partner pipelines.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "7c1e4a02b8d3"
down_revision: Union[str, None] = "50b273f73188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Added nullable first so existing rows survive; backfilled, then made NOT NULL.
    op.add_column(
        "pipeline_templates",
        sa.Column("tracks_partner", sa.Boolean(), nullable=True),
    )

    op.execute("UPDATE pipeline_templates SET tracks_partner = (type = 'partner')")

    op.alter_column(
        "pipeline_templates",
        "tracks_partner",
        nullable=False,
        server_default=sa.false(),
    )

    op.drop_column("pipeline_templates", "type")
    # The enum is a standalone type in Postgres and outlives its column.
    sa.Enum(name="pipeline_type").drop(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    pipeline_type = sa.Enum("direct", "partner", name="pipeline_type")
    pipeline_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "pipeline_templates",
        sa.Column("type", pipeline_type, nullable=True),
    )

    # Lossy by nature: any pipeline that is neither becomes 'direct', because the enum has
    # nowhere else to put it. This is the cost of going back to two categories.
    op.execute(
        "UPDATE pipeline_templates SET type = CASE WHEN tracks_partner THEN 'partner'::pipeline_type"
        " ELSE 'direct'::pipeline_type END"
    )

    op.alter_column("pipeline_templates", "type", nullable=False)
    op.drop_column("pipeline_templates", "tracks_partner")
