"""Restore the gen_random_uuid() default on the contact tables' primary keys

Revision ID: f4a9d3e02b18
Revises: e1c8a45b7f36
Create Date: 2026-08-12

`UUIDMixin` declares `id` with `server_default=func.gen_random_uuid()`, so nothing in the application
generates one — every insert relies on the database. Migrations b8e13d5a06c7 and e1c8a45b7f36 created
`contacts`, `contact_roles`, `deal_contacts` and `deal_roles` with a bare `sa.Column("id", sa.UUID())`
and no default, so the first insert into any of them failed with a not-null violation on `id`.

The tests did not catch this, and the reason is worth recording: `tests/conftest.py` builds its schema
with `Base.metadata.create_all`, which reads the mixin and *does* apply the default. So the test
database was correct and the migrated one was not — the two diverged silently, and every contacts test
passed against a schema no deployment would ever have.

The lesson for future migrations in this project: a hand-written `create_table` must repeat
`server_default=sa.text("gen_random_uuid()")` on `id`, because the mixin's version is invisible to
Alembic when the migration is not autogenerated.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f4a9d3e02b18"
down_revision: Union[str, None] = "e1c8a45b7f36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = ("contacts", "contact_roles", "deal_contacts", "deal_roles")


def upgrade() -> None:
    for table in TABLES:
        op.alter_column(table, "id", server_default=sa.text("gen_random_uuid()"))


def downgrade() -> None:
    # Restoring the broken state would only reintroduce the bug, but the downgrade has to be the
    # inverse of the upgrade for the chain to be reversible at all.
    for table in TABLES:
        op.alter_column(table, "id", server_default=None)
